apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-application
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
  project: default
  source:
    repoURL: https://github.com/jrg-sierra/argocdconf.git
    targetRevision: HEAD
    path: dev
  
  syncPolicy:
    syncOptions:
    - "CreateNamespace=true"
    automated:
      selfHeal: true
      prune: true 